include classpath("application.conf")
node-address { protocol = http, host = elasticmq, port = 9324, context-path = "" }
rest-sqs { enabled = true, bind-port = 9324, bind-hostname = "0.0.0.0" }
rest-stats { enabled = false }
queues {
  koyori-workflow-dlq { }
  koyori-activity-dlq { }
  koyori-workflow { defaultVisibilityTimeout = 60 seconds, deadLettersQueue { name = "koyori-workflow-dlq", maxReceiveCount = 5 } }
  koyori-activity { defaultVisibilityTimeout = 60 seconds, deadLettersQueue { name = "koyori-activity-dlq", maxReceiveCount = 5 } }
}
messages-storage { enabled = true, storage-directory = "/data/messages" }
